package com.spire.backend.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

/**
 * Maps to the 'users' table in MySQL.
 * Uses role_id FK to 'roles' table instead of embedded enum.
 *
 * @DynamicUpdate so Hibernate emits UPDATE statements that only touch
 * the columns that actually changed. Without it, every save rewrites
 * all columns, which is brittle when running against multiple
 * environments (MySQL dev vs Postgres prod) where naming strategies
 * can differ subtly.
 */
@Entity
@Table(name = "users")
@DynamicUpdate
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true, length = 255)
    private String email;

    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;

    @Column(name = "full_name", nullable = false, length = 100)
    private String fullName;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "role_id", nullable = false)
    private Role role;

    @Column(name = "avatar_url", length = 500)
    private String avatarUrl;

    @Column(columnDefinition = "TEXT")
    private String bio;

    // Profile-page extras — explicit @Column(name=...) so the mapping
    // can't get tripped up by per-environment naming strategies.
    @Column(name = "phone", length = 20)
    private String phone;

    @Column(name = "location", length = 255)
    private String location;

    @Column(name = "instructor_approved", nullable = false)
    @Builder.Default
    private Boolean instructorApproved = false;

    // Welcome-wizard flag. New signups land FALSE; flipped to TRUE the
    // first time the student dismisses the wizard or finishes the flow.
    @Column(name = "onboarding_completed", nullable = false)
    @Builder.Default
    private Boolean onboardingCompleted = false;

    @Column(name = "is_active", nullable = false)
    @Builder.Default
    private Boolean isActive = true;

    // ─── Email verification ─────────────────────────────────────────
    // Default false on signup — flipped true after the user enters
    // the 6-digit code we email them. Code + expiry are cleared once
    // consumed.
    //
    // The legacy {@code verificationToken} pair (UUID-based magic
    // link) is kept on the column model for backward compatibility
    // with rows in flight when the OTP gate shipped, but is no longer
    // populated by new signups.
    @Column(name = "email_verified", nullable = false)
    @Builder.Default
    private Boolean emailVerified = false;

    @Column(name = "verification_token", length = 64)
    private String verificationToken;

    @Column(name = "verification_expires_at")
    private LocalDateTime verificationExpiresAt;

    /** 6-digit numeric OTP. Stored as a string to preserve leading zeros. */
    @Column(name = "verification_code", length = 6)
    private String verificationCode;

    @Column(name = "verification_code_expires_at")
    private LocalDateTime verificationCodeExpiresAt;

    /** Failed-attempt counter for the OTP gate. Resets on success. */
    @Column(name = "verification_failed_attempts", nullable = false)
    @Builder.Default
    private Integer verificationFailedAttempts = 0;

    /**
     * Set when the user trips the brute-force lockout (5 wrong codes).
     * Cleared on a successful verification or once the time elapses.
     */
    @Column(name = "verification_locked_until")
    private LocalDateTime verificationLockedUntil;

    /**
     * Stamps the last "resend code" call so the rate limiter (60s
     * cooldown) has somewhere to look. The frontend countdown is
     * authoritative for UX, but we re-check server-side too.
     */
    @Column(name = "last_verification_resend_at")
    private LocalDateTime lastVerificationResendAt;

    /**
     * True once the user has accepted the Terms of Service. Default
     * false on signup; flipped true when the user enters the
     * agreement-acceptance OTP. The agreement gate filter rejects
     * authenticated requests for any user with this still false,
     * so the frontend can route them to /agreement.
     *
     * Pre-existing accounts (already in the DB before the gate
     * shipped) are grandfathered to true by DataSeeder so they're
     * not retroactively locked out.
     */
    @Column(name = "agreement_accepted", nullable = false)
    @Builder.Default
    private Boolean agreementAccepted = false;

    // ─── Password reset ─────────────────────────────────────────────
    // Single-use token + expiry generated by /forgot-password and
    // consumed by /reset-password. Cleared after a successful reset.
    @Column(name = "reset_token", length = 64)
    private String resetToken;

    @Column(name = "reset_token_expires_at")
    private LocalDateTime resetTokenExpiresAt;

    // ─── Inactivity nudge throttle ──────────────────────────────────
    // Stamped by the scheduled job every time a "we miss you" email
    // goes out. The job rate-limits to once per 14 days per user so
    // a chronically-idle account doesn't get pinged daily.
    @Column(name = "last_nudge_sent_at")
    private LocalDateTime lastNudgeSentAt;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
}
