package com.spire.backend.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

/**
 * Maps to the 'users' table in MySQL.
 * Uses role_id FK to 'roles' table instead of embedded enum.
 *
 * @DynamicUpdate so Hibernate emits UPDATE statements that only touch
 * the columns that actually changed. Without it, every save rewrites
 * all columns, which is brittle when running against multiple
 * environments (MySQL dev vs Postgres prod) where naming strategies
 * can differ subtly.
 */
@Entity
@Table(name = "users")
@DynamicUpdate
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true, length = 255)
    private String email;

    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;

    @Column(name = "full_name", nullable = false, length = 100)
    private String fullName;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "role_id", nullable = false)
    private Role role;

    @Column(name = "avatar_url", length = 500)
    private String avatarUrl;

    @Column(columnDefinition = "TEXT")
    private String bio;

    // Profile-page extras — explicit @Column(name=...) so the mapping
    // can't get tripped up by per-environment naming strategies.
    @Column(name = "phone", length = 20)
    private String phone;

    @Column(name = "location", length = 255)
    private String location;

    @Column(name = "instructor_approved", nullable = false)
    @Builder.Default
    private Boolean instructorApproved = false;

    // Welcome-wizard flag. New signups land FALSE; flipped to TRUE the
    // first time the student dismisses the wizard or finishes the flow.
    @Column(name = "onboarding_completed", nullable = false)
    @Builder.Default
    private Boolean onboardingCompleted = false;

    @Column(name = "is_active", nullable = false)
    @Builder.Default
    private Boolean isActive = true;

    // ─── Email verification ─────────────────────────────────────────
    // Default false on signup — flipped true when the student clicks
    // the verification link. Token+expiry are cleared once consumed.
    // Existing pre-verification accounts default to false; admins can
    // grandfather them in via DB if needed.
    @Column(name = "email_verified", nullable = false)
    @Builder.Default
    private Boolean emailVerified = false;

    @Column(name = "verification_token", length = 64)
    private String verificationToken;

    @Column(name = "verification_expires_at")
    private LocalDateTime verificationExpiresAt;

    // ─── Password reset ─────────────────────────────────────────────
    // Single-use token + expiry generated by /forgot-password and
    // consumed by /reset-password. Cleared after a successful reset.
    @Column(name = "reset_token", length = 64)
    private String resetToken;

    @Column(name = "reset_token_expires_at")
    private LocalDateTime resetTokenExpiresAt;

    // ─── Inactivity nudge throttle ──────────────────────────────────
    // Stamped by the scheduled job every time a "we miss you" email
    // goes out. The job rate-limits to once per 14 days per user so
    // a chronically-idle account doesn't get pinged daily.
    @Column(name = "last_nudge_sent_at")
    private LocalDateTime lastNudgeSentAt;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
}
